### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'pythonapi'

### ISSUE THREAD

**Issue by giordano** [cjdoris/PythonCall.jl#165]
I'm trying to switch from `Conda.jl` to `CondaPkg.jl` for running the tests of `Reproject.jl`.  So far I managed to get only Linux to work (which is already a step forward compared to zero systems with `Conda.jl`!), but tests at revision https://github.com/JuliaAstro/Reproject.jl/tree/067aa9b5e3f39cc9d30cc6cd446d988c94de4a7b failed on macOS and Windows: https://github.com/JuliaAstro/Reproject.jl/runs/6149308802?check_suite_focus=true.  This is an excerpt of the log:
```
Traceback (most recent call last):
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 395, in <module>
    main()
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 391, in main
    parser.exit(cli_find_libpython(**vars(ns)))
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 356, in cli_find_libpython
    print_all(finding_libpython())
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 340, in print_all
    for x in items:
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 149, in uniquifying
    for x in items:
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 316, in finding_libpython
    for path in candidate_paths():
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 149, in uniquifying
    for x in items:
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 214, in candidate_paths
    yield linked_libpython()
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 67, in linked_libpython
    return _linked_libpython_unix()
  File "/Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py", line 86, in _linked_libpython_unix
    ctypes.cast(ctypes.pythonapi.Py_GetVersion, ctypes.c_void_p),
AttributeError: module 'ctypes' has no attribute 'pythonapi'
ERROR: LoadError: InitError: failed process: Process(setenv(`/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jl_HZVLpI/.CondaPkg/env/bin/python /Users/runner/.julia/packages/PythonCall/XgP8G/src/cpython/find_libpython.py --list-all`,["PATH=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jl_HZVLpI/.CondaPkg/env/bin:/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jl_HZVLpI/.CondaPkg/env/condabin:/Users/runner/.julia/artifacts/bfd9e864c155203704978fba74583859175640d2/bin:/Users/runner/hostedtoolcache/julia/1.6.6/x64/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.5/x64", "GITHUB_RUN_NUMBER=12", "GITHUB_REF_NAME=9/merge", "RUNNER_ARCH=X64", "PERFLOG_LOCATION_SETTING=RUNNER_PERFLOG", "NUNIT3_PATH=/Library/Developer/nunit/3.6.0", "NVM_CD_FLAGS=", "GITHUB_ACTOR=giordano", "ANDROID_NDK_LATEST_HOME=/Users/runner/Library/Android/sdk/ndk/23.1.7779620", "USER=runner"  …  "BOOTSTRAP_HASKELL_NONINTERACTIVE=1", "RUNNER_TEMP=/Users/runner/work/_temp", "JAVA_HOME_11_X64=/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.14-101/x64/Contents/Home/", "GOROOT_1_16_X64=/Users/runner/hostedtoolcache/go/1.16.15/x64", "GITHUB_REPOSITORY_OWNER=JuliaAstro", "MAMBA_ROOT_PREFIX=/Users/runner/.julia/scratchspaces/0b3b1443-0f03-428d-bdfb-f27f9c1191ea/root", "GITHUB_EVENT_NAME=pull_request", "OPENBLAS_MAIN_FREE=1", "ANDROID_NDK_HOME=/Users/runner/Library/Android/sdk/ndk-bundle", "AGENT_TOOLSDIRECTORY=/Users/runner/hostedtoolcache"]), ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:538 [inlined]
  [2] (::Base.var"#644#645"{Base.Process})()
    @ Base ./process.jl:319
  [3] iterate(itr::Base.EachLine{Base.PipeEndpoint}, state::Nothing) (repeats 2 times)
    @ Base ./io.jl:1014
  [4] _collect(cont::UnitRange{Int64}, itr::Base.EachLine{Base.PipeEndpoint}, #unused#::Base.HasEltype, isz::Base.SizeUnknown)
    @ Base ./array.jl:613
  [5] collect
    @ ./array.jl:602 [inlined]
  [6] #readlines#340
    @ ./io.jl:551 [inlined]
  [7] readlines
    @ ./io.jl:551 [inlined]
  [8] init_context()
    @ PythonCall.C ~/.julia/packages/PythonCall/XgP8G/src/cpython/context.jl:106
  [9] __init__()
    @ PythonCall.C ~/.julia/packages/PythonCall/XgP8G/src/cpython/CPython.jl:21
 [10] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:696
 [11] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:782
 [12] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1020
 [13] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:936
 [14] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:923
 [15] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [16] top-level scope
    @ none:6
during initialization of module C
in expression starting at /Users/runner/work/Reproject.jl/Reproject.jl/test/runtests.jl:3
```
The Conda [environment](https://github.com/JuliaAstro/Reproject.jl/blob/067aa9b5e3f39cc9d30cc6cd446d988c94de4a7b/CondaPkg.toml) is
```toml
channels = ["astropy", "conda-forge"]

[deps]
python = "=3.7"
astropy = "=4.3"
reproject = "=0.5"
```

**Comment by giordano** [comment]
Actually, the Windows jobs failed with a different error:
```
error    libmamba Error opening for writing "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\jl_2GsAbw\\.CondaPkg\\env\\Scripts\\wheel-script.py": No such file or directory
error    libmamba Error opening for writing "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\jl_2GsAbw\\.CondaPkg\\env\\Scripts\\wheel.exe": No such file or directory
critical libmamba The system cannot find the path specified.
```

**Comment by cjdoris** [comment]
The major difference is that on Mac and Windows, PyPy is being installed instead of CPython, but only CPython is supported by PythonCall. I'm not sure how to get Conda to only install CPython.

**Comment by cjdoris** [comment]
OK I have made a small change to CondaPkg and PythonCall, which ensures that only CPython is installed (not PyPy). This issue shouldn't occur again. I'm releasing a version today.
