### ISSUE TITLE
PythonCall.jl did not start properly when import juliacall

### ISSUE THREAD

**Issue by ywlds** [cjdoris/PythonCall.jl#188]
>>> import juliacall
[juliapkg] Locating Julia ^1.6
[juliapkg] Using Julia 1.6.0 at /opt/tiger/DMET/julia-1.6.0/bin/julia
[juliapkg] Using Julia project at /home/tiger/anaconda3/julia_env
[juliapkg] Installing packages:
           julia> import Pkg
           julia> Pkg.add([Pkg.PackageSpec(name="PythonCall", uuid="6099a3de-0909-46bc-b1f4-468b9a2dfc0d")])
           julia> Pkg.resolve()
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `~/anaconda3/julia_env/Project.toml`
  [6099a3de] + PythonCall v0.9.1
    Updating `~/anaconda3/julia_env/Manifest.toml`
  [992eb4ea] + CondaPkg v0.2.10
  [9a962f9c] + DataAPI v1.10.0
  [e2d170a0] + DataValueInterfaces v1.0.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [0f8b85d8] + JSON3 v1.9.5
  [1914dd2f] + MacroTools v0.5.9
  [0b3b1443] + MicroMamba v0.1.8
  [bac558e1] + OrderedCollections v1.4.1
  [69de0a69] + Parsers v2.3.2
  [6099a3de] + PythonCall v0.9.1
  [ae029012] + Requires v1.3.0
  [6c6a2e73] + Scratch v1.1.0
  [856f2bd8] + StructTypes v1.8.1
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.7.0
  [e17b2a0c] + UnsafePointers v1.0.0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [83775a58] + Zlib_jll
  [8e850ede] + nghttp2_jll
  [3f19e933] + p7zip_jll
  No Changes to `~/anaconda3/julia_env/Project.toml`
  No Changes to `~/anaconda3/julia_env/Manifest.toml`
ERROR: MethodError: no method matching activate(::String; io=Base.DevNull())
Closest candidates are:
  activate(::AbstractString; shared, temp) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1407 got unsupported keyword argument "io"
  activate(; temp, shared) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1381 got unsupported keyword argument "io"
  activate(::Function, ::AbstractString) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1448 got unsupported keyword argument "io"
Stacktrace:
 [1] kwerr(::NamedTuple{(:io,), Tuple{Base.DevNull}}, ::Function, ::String)
   @ Base ./error.jl:157
 [2] top-level scope
   @ none:4Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tiger/anaconda3/lib/python3.7/site-packages/juliacall/__init__.py", line 150, in <module>
    init()
  File "/home/tiger/anaconda3/lib/python3.7/site-packages/juliacall/__init__.py", line 144, in init
    raise Exception('PythonCall.jl did not start properly')
Exception: PythonCall.jl did not start properly

**Comment by ywlds** [comment]
Note the julia PythonCall can be startup individually as 

![image](https://user-images.githubusercontent.com/14145559/174987491-95e4b9ea-a17e-46dd-ba41-a8bdd05d9da4.png)

**Comment by ywlds** [comment]
with the setting 
![image](https://user-images.githubusercontent.com/14145559/174987850-bf27854d-19ee-4219-926f-3059a42a2ea0.png)

**Comment by ywlds** [comment]
Thanks, I will try this.

**Comment by ywlds** [comment]
I directly upgrade to 1.7.3. Now it works.
